### ISSUE TITLE
Export problems

### ISSUE THREAD

**Issue by Vikort** [ostis-ai/sc-machine#125]
**Describe the bug**
There are several problems regarding the export:
1. If you export existing knowledge to .gwf format, on next rebuild it doesn't get merged properly (you get 2 copies of sc-links)
2. `.gwf` export doesn't export file format (HTML and images are borked after rebuild) 

<img width="939" alt="image" src="https://user-images.githubusercontent.com/43214067/182617210-4e237dc7-2543-4ead-828c-861fc22e5931.png">

_Originally posted by @FallenChromium

**To Reproduce**
1. Go to `scg_code` entity
2. Click on export button in `SCg code` mode
3. Put exported file to kb and rebuild kb.
4. Run system and see error

**Expected behavior**
Correct links and no duplicates.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by NikitaZotov** [comment]
May be, problem occurs beacuse file doesn't clear. I'll check it and answer you

**Comment by NikitaZotov** [comment]
I think that this problem is outdated
