### ISSUE TITLE
Passing wrong payload to sc-server's `create_elements_by_scs` causes a crash

### ISSUE THREAD

**Issue by FallenChromium** [ostis-ai/sc-machine#136]
**Describe the bug**
After sending an empty payload to `create_elements_by_scs` method of SC-JSON API provided by `sc-server` it crashed with SIGABRT.

**To Reproduce**
1. Start sc-server
2. Establish a websocket connection
3. Send empty payload to `create_elements_by_scs` endpoint

**Expected behavior**
I am not sure if it should raise an error or pass it as a valid construction, but it definitely shouldn't stop execution.

**Screenshots**
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/43214067/186251929-29bc411c-44ba-42ef-a5c4-566b40ee9bd9.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 in Docker
 - Version 0.7.0

**Comment by NikitaZotov** [comment]
Fixed in https://github.com/ostis-ai/sc-machine/pull/137
