### ISSUE TITLE
Test behavior of the system without empty space in storage

### ISSUE THREAD

**Issue by AlexandrZagorskiy** [ostis-ai/sc-machine#141]
**Is your feature request related to a problem? Please describe.**
What should system do if there is no space left in the memory storage? 

**Describe the solution you'd like**
I think it should looks like starting version of platform with separate test config, which should decrease the amount of possible created elements in the sc-memory to the minimum level. Test should fix the behavior of the server for such situation.

**Comment by NikitaZotov** [comment]
Solved in https://github.com/ostis-ai/sc-machine/blob/main/sc-memory/tests/sc-memory/common/test_sc_elements.cpp
