### ISSUE TITLE
Possible invalid state during template search

### ISSUE THREAD

**Issue by NikiforovSergei** [ostis-ai/sc-machine#186]
**Describe the bug**
Possible invalid state during template search, depending on KB content.

**To Reproduce**
To reproduce the behavior add somewhere and run the next test:
```
TEST_F(templateSearchTest, notEmptyResultTest)
{
  ScMemoryContext & context = *m_ctx;

  loader.loadScsFile(context, TEST_FILES_DIR_PATH + "corresponding_construction.scs");
  loader.loadScsFile(context, TEST_FILES_DIR_PATH + "template.scs");

  ScAddr templateAddr = context.HelperFindBySystemIdtf("template");
  EXPECT_TRUE(templateAddr.IsValid());

  ScTemplate scTemplate;
  context.HelperBuildTemplate(scTemplate, templateAddr);

  ScTemplateSearchResult searchResult;
  try
  {
    context.HelperSearchTemplate(scTemplate, searchResult);
  }
  catch (utils::ScException & ex)
  {
    SC_LOG_ERROR(ex.Description());
  }
}
```
Where `corresponding_construction.scs` content is:
```
message => nrel_test_relation: set;;
set -> structure;;
structure -> test_node;;
```
and the `template.scs` content is:
```
@template = [*
    message _=> nrel_test_relation:: _set;;
    _set _-> _structure;;
    _structure _-> _test_class;;
*];;
@template => nrel_system_identifier: [template];;
```

**Expected behavior**
Successful test run.

**Desktop (please complete the following information):**
 - OS: Mint 20.3
 - sc-machine 0.7.0
 
**Additional context**
Problem stays even if we leave in `corresponding_construction.scs` only:
```
message => nrel_test_relation: set;;
```
Disappears if we remove all content or replace it with something non-suitable:
```
message -> structure;;
```

**Comment by NikitaZotov** [comment]
This PR https://github.com/ostis-ai/sc-machine/pull/194 can help you with this problem
