### ISSUE TITLE
SCs-file dumps kb-builder

### ISSUE THREAD

**Issue by artrayme** [ostis-ai/sc-machine#189]
When I try to build a kb with my scs-files, I have an error message. This error message describes an internal error in the sc-memory. But I'm expecting information about a syntax error in my scs.

Environment: 
- oficial docker image 
- last sc-machine version (from this repo)

Error message:
![image](https://user-images.githubusercontent.com/78550819/200175820-1e38409a-979c-479c-8232-cdf45f018779.png)

Full log:
[log.txt](https://github.com/ostis-ai/sc-machine/files/9946020/log.txt)

My scs-file:
[test.txt](https://github.com/ostis-ai/sc-machine/files/9946022/test.txt)

**Comment by NikitaZotov** [comment]
Fixed by https://github.com/ostis-ai/sc-machine/pull/217
