### ISSUE TITLE
Flag -v for sc-server does saves memory on exit

### ISSUE THREAD

**Issue by kilativ-dotcom** [ostis-ai/sc-machine#248]
**Describe the bug**
I wanted to use -v flag so every time I  start sc-server knowledge base would have initial state

**To Reproduce**
1. Go to scripts
2. change run_sc_server.sh so last line will launch sc-server with flag -v
3. run sc server and sc web
4. write in search panel "Что такое" and see 5 results in prompt
5. navigate through some nodes
6. restart sc-server and sc-web
7. write in search panel "Что такое" and see more than 5 results in prompt

**Expected behavior**
Expected that -v flag will stop sc-server from saving context on exit

**Screenshots**
![search panel after first start](https://user-images.githubusercontent.com/56753138/220390718-b6e3dc10-6d3b-4cf4-9bea-840b84cc4869.png)
![search panel after restart](https://user-images.githubusercontent.com/56753138/220390844-8939bc49-ee36-4884-9ed3-8af93f5afd87.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by NikitaZotov** [comment]
Fixed in 0.10.0
