### ISSUE TITLE
[scs] Allow specification of the structure into this structure itself

### ISSUE THREAD

**Issue by ShunkevichDV** [ostis-ai/sc-machine#40]
**Is your feature request related to a problem? Please describe.**
in OSTIS Standard there are a lot of constructions like this^

struct1
[*
=>nrel_idtf:
    [Identifier1];;
*];;

We use them when we need include the structure specification into this structure itself. There are no other ideas how to do that shortly.

**Describe the solution you'd like**
Support this type of construction in scs-builder and in SCs grammar. Shortly the idea is - when scs-sentence is included in scs-contour and the first element of this sentence is not presented, that means that the first element of this sentence is the structure, defined by this scs-contour.

**Describe alternatives you've considered**
I don't see other "normal" ways, only idea is to write everything in triples and give temporal names to all sc-elements

**Comment by NikitaZotov** [comment]
Solved in #53. Check it, please.
