### ISSUE TITLE
Communication between `kb_scripts` and `build_kb.py` is shallow

### ISSUE THREAD

**Issue by FallenChromium** [ostis-ai/sc-machine#50]
**Is your feature request related to a problem? Please describe.**
After the merge of #43, all scripts related to building KBs will be moved to sc-machine repository. There's a problem with these scripts: kb_scripts use an error log file (...existence of it, rather) as a measure to message `build_kb.py` that something went wrong.  

**Describe the solution you'd like**
The UNIX way for scripts to communicate with each other is by using exit codes - non-zero exit code would indicate that there was a problem.

**Describe alternatives you've considered**
Considering that there are non-fatal errors in kb_scripts, I would advise to establish an exit code system, so that we can be vocal about the errors, but continue the build process anyway. Alternatively, we could expose a standardised `prepare()` function (or something along those lines) in kb_scripts and import the logic as modules opposed to running in a subprocess.

**Comment by NikitaZotov** [comment]
I suppose that if the scripts are written in the same language, then a common wrapper can be made for them and the question will be removed.

**Comment by NikitaZotov** [comment]
I think that this problem is outdated
