### ISSUE TITLE
Add healthcheck endpoint to sc-server

### ISSUE THREAD

**Issue by VasKho** [ostis-ai/sc-machine#99]
**Is your feature request related to a problem? Please describe.**
After we deploy platform on server we regularly need to check its state. Now it's implemented in inconvenient way via external scripts .

**Describe the solution you'd like**
Add `/health` endpoint to `sc-server`.

**Comment by NikitaZotov** [comment]
Solved by https://github.com/ostis-ai/sc-machine/pull/140
